---
- name: test playbook
  hosts: win
  tasks:
    - name: test poweshell script 
      script: winrm_memory_hotfix.ps1
      register: result

    - name: check result
      debug:
        var: result

        
